---
- name: download play framework
  shell: wget https://downloads.typesafe.com/play/2.2.6/play-2.2.6.zip creates=/home/vagrant/play-2.2.6.zip

- name: unzip play framework
  shell: unzip -d /home/vagrant/play-framework play-2.2.6.zip creates=/home/vagrant/play-framework/play-2.2.6

- name: add play to path
  shell: export PATH=$PATH:/home/vagrant/play-framework/play-2.2.6
